# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


pool:
  vmImage: 'ubuntu-latest'

steps:
- task: GitHubRelease@1
  displayName: 'GitHub release (create)'
  inputs:
    gitHubConnection: github
    target: master
    tagSource: gitTag
    tagPattern: 'd.*'
    title: latest rel
    releaseNotesSource: inline
    changeLogCompareToRelease: lastNonDraftReleaseByTag
    changeLogCompareToReleaseTag: 'd.*'
    changeLogType: issueBased
    changeLogLabels: '[{"label": "trust", "displayName": "Trust Issues"}, {"label": "bug", "displayName": "Bugs Fixed", "state": "closed"}]'
